---
title: "Data Visualizations"
---

```{r include = FALSE}
#---------------------------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE,
                      fig.align = "center", out.width = "100%", out.height = "100%")
#---------------------------------------------------------------------
# Load Packages
#---------------------------------------------------------------------
library(tidyverse)
library(interactions)
library(readxl)
library(fredr)
library(lubridate)
library(scales)
library(countrycode)
#---------------------------------------------------------------------
# Load Data
#---------------------------------------------------------------------
mega_combined_vars_df_SUBSET_added_vars <- readRDS("mega_combined_vars_df_SUBSET_added_vars.rds")
#---------------------------------------------------------------------
new_mega_edits_df <- readRDS("new_mega_edits_df.rds")
#---------------------------------------------------------------------
tax_expenditure_distriibution_df <- read_excel("tax expenditure distriibution.xlsx")
#---------------------------------------------------------------------
tax_expenditure_distriibution_df_v2 <- readRDS("tax_expenditure_distriibution_df_v2.rds")
#---------------------------------------------------------------------
pwt_mega_df <- readRDS("~/github-website/pwt_mega_df.rds")
#---------------------------------------------------------------------
fedr_df_v2_copy <- readRDS("fedr_df_v2_copy.rds")
#---------------------------------------------------------------------
fredr_set_key("4ea646af5b37ba1c45a0890c7a04f2dc")
#---------------------------------------------------------------------
```

## Barplots

```{r tax_expenditure_dist, cache=TRUE, fig.width=20, fig.asp=0.8}
#--------------------------------------------------------------------------------
# Solid Barplot
#--------------------------------------------------------------------------------
tax_expenditure_distriibution_df_v2 %>%
  mutate(income_group = factor(income_group, c("first_quintile", "second_quintile", "middle_quintile", "fourth_quintile", "top_quintile", "top_1pct"))) %>%
  filter(income_group %in% c("first_quintile", "second_quintile", "middle_quintile", "fourth_quintile", "top_quintile", "top_1pct")) %>%
  ggplot(aes(income_group, income_tax_expenditure_share)) +
  geom_bar(stat = "identity", position = position_stack(reverse = TRUE), width = 0.5) +
  labs(title = "Share of Income Tax Expenditures",
       subtitle = "United States (2019)",
       x = "Income Group",
       y = "Share of Income Tax Expenditures (%)",
       caption = "
       Data source(s): Congressional Budget Office") +
  theme_bw(base_size = 35) +
  theme(text = element_text(face = 'bold'),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.position = "bottom",
        legend.box.background = element_rect(colour = "black")) +
  scale_x_discrete(breaks = c("first_quintile", "second_quintile", "middle_quintile", "fourth_quintile", "top_quintile", "top_1pct"),
                   labels = c("Q1", "Q2", "Q3", "Q4", "Q5", "Top 1%"))
#--------------------------------------------------------------------------------
```

***

```{r debt_bar, cache=TRUE, fig.width=12, fig.asp=0.8}
new_mega_edits_df %>%
  filter(iso3 %in% c("USA", "GBR", "DEU", "JPN"),
         year == 2015) %>%
  select(country_name,
         pct_gdp_corporate_debt,
         pct_gdp_govt_debt,
         pct_gdp_total_household_debt) %>%
  rename("Corporate" = pct_gdp_corporate_debt,
         "Household" = pct_gdp_total_household_debt,
         "Government" = pct_gdp_govt_debt) %>%
  gather(key = "debt", value = "value", -country_name) %>%
  ggplot(aes(fill=debt, y=value, x=country_name)) + 
  geom_bar(position="dodge", stat="identity") +
  theme_bw(base_size = 20) +
  labs(x = " ",
       y = "Debt Total (% GDP)",
       title = "Cross-National Debt Totals (2015)",
       caption = "
       Data Source(s): Global Debt Database",
       fill = "Debt Type") +
  theme(text = element_text(face = 'bold'),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "right",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))
#--------------------------------------------------------------------------------
```

***

```{r wash_plot3, echo=FALSE, warning=FALSE, cache=TRUE}
#--------------------------------------------------------------------------------------
map_dfr(c("SMS11000009091000001",
          "DCLEIH",
          "SMU11000006056130001SA"),
        fredr,
        frequency = "m",
        units = "lin") %>%
  mutate(date = ymd(date),
         series_id = case_when(series_id == "SMS11000009091000001" ~ "Federal Governmentt",
                               series_id == "DCLEIH" ~ "Leisure/Hospitality",
                               series_id == "SMU11000006056130001SA" ~ "Business/Professional Services")) %>%
  filter(date == "2022-05-01") %>%
  ggplot(aes(y=value, x=series_id)) + 
  geom_bar(position="dodge", stat="identity", width = 0.5) +
  theme_bw() +
  labs(x = "",
       y = "Number of Employees (Thousands)",
       title = "Washington, DC Area (May 2022)",
       caption = "
       Data Source(s): Federal Researve Economic Data (FRED)") +
  theme(text = element_text(face = 'bold'),
        plot.caption = element_text(hjust = 0, face = "bold"),
        plot.caption.position = "plot")

```

***

```{r investment, echo=FALSE, warning=FALSE, cache=TRUE, fig.width=10, fig.asp=0.9}
pwt_mega_df %>%
  mutate(pwt_pct_gdp_investment_transport = (pwt_investment_transport_equip_current_LCU/pwt_gdp_current_LCU)*100,
         pwt_pct_gdp_investment_structures = (pwt_investment_res_nonres_structures_current_LCU/pwt_gdp_current_LCU)*100,
         pwt_pct_gdp_investment_machinery = (pwt_investment_machinery_plus_equipment_current_LCU/pwt_gdp_current_LCU)*100) %>%
  filter(country_code_ISO3 %in% c("CHN", "USA", "GBR", "FRA", "JPN")) %>%
  filter(year == 2017) %>%
  mutate(countries = countrycode(country_code_ISO3, origin = 'iso3c',
                                 destination = 'p4.name')) %>%
  select(countries,
         pwt_pct_gdp_investment_transport,
         pwt_pct_gdp_investment_structures,
         pwt_pct_gdp_investment_machinery) %>%
  rename("Transportation" = pwt_pct_gdp_investment_transport,
         "Construction" = pwt_pct_gdp_investment_structures,
         "Machinery" = pwt_pct_gdp_investment_machinery) %>%
  gather(key = "variable", value = "value", -countries) %>%
  ggplot(aes(countries, value, fill = variable)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_bw(base_size = 15) +
  labs(x = " ",
       y = "Percent GDP (%)",
       fill = "Investment Type",
       caption = "
       Data source(s): Penn World Table",
       title = "Cross-National Capital Investments (2017)",
       subtitle = "Percent of GDP (%)") +
  theme(text = element_text(face = 'bold'),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "right",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"))
```

***

## Lineplots

```{r wash_plot1, echo=FALSE, warning=FALSE, cache=TRUE, fig.width=18, fig.asp=0.6}
#--------------------------------------------------------------------------------------
# fedr ggplot
#--------------------------------------------------------------------------------------
map_dfr(c("SMU11000000500000003",
          "DCUCSFRCONDOSMSAMID",
          "LBSSA11"),
        fredr,
        frequency = "m",
        units = "pch") %>%
  mutate(date = ymd(date),
         series_id = case_when(series_id == "SMU11000000500000003" ~ "Average Hourly Earnings",
                               series_id == "DCUCSFRCONDOSMSAMID" ~ "Zillow Home Value Index",
                               series_id == "LBSSA11" ~ "Labor Force Participation Rate")) %>%
  filter(date >= "2019-01-01") %>%
  ggplot(mapping = aes(x = date, y = value)) +
  geom_line() +
  geom_smooth(method = "loess") +
  theme_bw(base_size = 30) +
  labs(x = "Month-Year",
       y = "Percent Change (%)",
       title = "Washington, DC Area",
       subtitle = "Monthly Economic Data (2019 - 2022)",
       caption = "
       Data Source(s): Federal Researve Economic Data (FRED)") +
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        axis.title.x = element_text(vjust = -1.5),
        text = element_text(face = 'bold'),
        plot.caption = element_text(hjust = 0, face = "bold"),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_date(date_labels = "%b-%Y",
               date_breaks = "5 month") +
  facet_wrap(vars(series_id))
```

***

```{r wash_plot2, echo=FALSE, warning=FALSE, cache=TRUE, fig.width=10, fig.asp=0.8}
map_dfr(c("DCBPPRIVSA"),
        fredr,
        frequency = "m",
        units = "pch") %>%
  mutate(date = ymd(date),
         series_id = case_when(series_id == "DCBPPRIVSA" ~ "New Housing Permits")) %>%
  filter(date >= "2019-01-01") %>%
  ggplot(mapping = aes(x = date, y = value)) +
  geom_line() +
  geom_smooth(method = "loess") +
  theme_bw(base_size = 20) +
  labs(x = "Month-Year",
       y = "Monthly Change",
       title = "Washington, DC Area",
       subtitle = "Monthly Economic Data (2019 - 2022)",
       caption = "
       Data Source(s): Federal Researve Economic Data (FRED)") +
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        axis.title.x = element_text(vjust = -1.5),
        text = element_text(face = 'bold'),
        plot.caption = element_text(hjust = 0, face = "bold"),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_date(date_labels = "%b-%Y",
               date_breaks = "4 month") +
  scale_y_continuous(limits = c(-900, 2850),
                     labels = label_percent(big.mark = ",")) +
  facet_wrap(vars(series_id))
```

***

```{r fed_funds, cache=TRUE}
#--------------------------------------------------------------------------------
fedr_df_v2_copy %>%
  filter(year >= 1970) %>%
  filter(series_id %in% c('Federal Funds Rate')) %>%
  ggplot(mapping = aes(x = date, y = value)) +
  geom_line() +
  geom_smooth(method = "loess") +
  theme_bw() +
  labs(x = "Month-Year",
       y = "Federal Rate (%)",
       title = "Federal Funds Effective Rate (%)") +
  theme(axis.text.x = element_text(angle = 35, hjust = 1),
        axis.title.x = element_text(vjust = -1),
        text = element_text(face = 'bold'),
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_date(date_labels = "%b-%Y",
               date_breaks = "48 month") +
  geom_vline(xintercept=as.numeric(fedr_df_v2_copy$date[299]), linetype="longdash", color = "red") +
  geom_label(label="Volcker Shock",
             x = as.numeric(fedr_df_v2_copy$date[237]),
             y = 18.5,
             label.padding = unit(0.275, "lines"),
             label.size = 0.15,
             color = "black",
             fill = "#69b3a2")
#--------------------------------------------------------------------------------
```
***

```{r gdp_growth, echo=FALSE, warning=FALSE, cache=TRUE, fig.width=8, fig.asp=0.8}
mega_combined_vars_df_SUBSET_added_vars %>%
  filter(country_code_ISO3 %in% c("CAN", "USA", "GBR", "FRA", "DEU", "JPN")) %>%
  select(country_name, year,
         pwt_gdp_growth_2017_ppp_5yr_MA) %>%
  rename("GDP Growth (5yr MA)" = pwt_gdp_growth_2017_ppp_5yr_MA) %>%
  gather(key = "gdp", value = "value", -country_name, -year) %>%
  ggplot(aes(x = year, y = value)) +
  theme_bw() +
  geom_smooth(method = 'lm') +
  geom_line() +
  labs(y = "Percent (%)",
       x = "Year",
       title = "GDP Growth (5yr Moving Average)",
       subtitle = "G6 Countries",
       caption = "
       Data source(s): Penn World Tables") +
  theme(axis.text.x = element_text(angle=35, hjust=1),
        axis.title.x = element_text(vjust = -1.5),
        text = element_text(face = 'bold'),
        panel.background = element_rect(colour = "black"),
        plot.caption = element_text(hjust = 0, face = "bold"),
        plot.caption.position = "plot",
        legend.position="bottom",
        strip.text.x = element_text(face = "bold"),
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_continuous(limits = c(1960, 2020), breaks = seq(1960, 2020, by = 10)) +
  facet_wrap(vars(country_name))
```

***

```{r inequality_plot, echo=FALSE, warning=FALSE, cache=TRUE, fig.width=8, fig.asp=0.8}
#--------------------------------------------------------------------------------
mega_combined_vars_df_SUBSET_added_vars %>%
  filter(country_code_ISO3 %in% c("CAN", "USA", "GBR",
                                  "NOR", "DEU", "FRA")) %>%
  rename("Private Social Spending (% GDP)" = oecd_total_private_socspend_full_pop_pct_gdp,
         "Top 1% Income Share" = WID_pre_tax_income_share_top_1pct) %>%
  select(country_name, year, "Private Social Spending (% GDP)", "Top 1% Income Share") %>%
  gather(key = "Type", value = "value", -country_name, -year) %>%
  ggplot(aes(x = year, y = value)) +
  geom_line(aes(linetype = Type)) +
  labs(title = "Private Welfare Spending vs. Income Inequality",
       x = "Year",
       y = "Percent (%)",
       linetype = "",
       caption = "
       Data source(s): OECD Social Protection Database & World Inequality Database") +
  theme_bw() +
  theme(text = element_text(face = 'bold'),
        axis.text.x = element_text(angle = 35, hjust = 1),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, by = 10)) +
  facet_wrap(vars(country_name))
#--------------------------------------------------------------------------------
```

***

```{r asset_plot, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.width=8, fig.asp=0.8}

mega_combined_vars_df_SUBSET_added_vars %>%
  filter(country_code_ISO3 %in% c("CAN", "USA", "GBR",
                                  "FRA", "JPN", "DEU")) %>%
  select(country_name, year,
         WID_pct_gdp_corporate_financial_assets,
         WID_pct_gdp_corporate_nonfinancial_assets) %>%
  rename("Financial Assets" = WID_pct_gdp_corporate_financial_assets,
         "Nonfinancial Assets" = WID_pct_gdp_corporate_nonfinancial_assets) %>%
  gather(key = "Type", value = "value", -country_name, -year) %>%
  ggplot(aes(x = year, y = value)) +
  geom_line(aes(linetype = Type)) +
  labs(title = "Cross-National Corporate Asset Levels (% GDP)",
       x = "Year",
       y = "Percent of GDP (%)",
       linetype = "",
       caption = "
       Data source(s): World Inequality Database") +
  theme_bw() +
  theme(text = element_text(face = 'bold'),
        axis.text.x = element_text(angle = 35, hjust = 1),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, by = 10)) +
  facet_wrap(vars(country_name))
```

***

```{r ineq_plot, echo=FALSE, message=FALSE, warning=FALSE, cache=TRUE, fig.width=8, fig.asp=0.75}
#--------------------------------------------------------------------------------
mega_combined_vars_df_SUBSET_added_vars %>%
  group_by(year) %>%
  filter(country_code_ISO3 %in% c("CAN", "USA", "GBR",
                                  "JPN", "DEU", "FRA", "ITA")) %>%
  mutate(WID_pre_tax_income_share_bottom_50pct = mean(WID_pre_tax_income_share_bottom_50pct, na.rm = TRUE),
         WID_pre_tax_income_share_top_1pct = mean(WID_pre_tax_income_share_top_1pct, na.rm = TRUE)) %>%
  distinct(year, .keep_all = TRUE) %>%
  select(year, WID_pre_tax_income_share_top_1pct, WID_pre_tax_income_share_bottom_50pct) %>%
  rename("Bottom 50%" = WID_pre_tax_income_share_bottom_50pct,
         "Top 1%" = WID_pre_tax_income_share_top_1pct) %>%
  gather(key = "variable", value = "value", -year) %>%
  ggplot(aes(x = year, y = value)) +
  geom_line(aes(linetype = variable)) +
  theme_bw() +
  labs(x = "Year",
       y = "Share of National Income (%)",
       caption = "
       Data source(s): World Inequality Database",
       title = "Average National Income Share in G7 Countries") +
  theme(text = element_text(face = 'bold'),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.title = element_blank(),
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_continuous(limits = c(1970, 2020), breaks = seq(1970, 2020, by = 10))

```

***

```{r debt, echo=FALSE, warning=FALSE, cache=TRUE, fig.width=8, fig.asp=0.8}
 mega_combined_vars_df_SUBSET_added_vars %>%
  filter(country_code_ISO3 %in% c("CAN", "USA", "GBR", "FRA", "JPN", "DEU")) %>%
  select(country_name, year, WID_pct_gdp_corporate_debt, WID_pct_gdp_govt_debt) %>%
  rename("Corporate Debt" = WID_pct_gdp_corporate_debt,
         "Government Debt" = WID_pct_gdp_govt_debt) %>%
  gather(key = "Type", value = "value", -country_name, -year) %>%
  ggplot(aes(x = year, y = value)) +
  geom_line(aes(linetype = Type)) +
  labs(title = "Cross-National Debt Levels (% GDP)",
       x = "Year",
       y = "Percent of GDP (%)",
       linetype = "",
       caption = "
       Data source(s): World Inequality Database") +
  theme_bw() +
  theme(text = element_text(face = 'bold'),
        axis.text.x = element_text(angle = 35, hjust = 1),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        strip.text.x = element_text(face = "bold"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  scale_x_continuous(limits = c(1980, 2020), breaks = seq(1980, 2020, by = 10)) +
  facet_wrap(vars(country_name))
```

***

## Scatterplots

```{r ineq_scatter, echo=FALSE, warning=FALSE, cache=TRUE, fig.asp=0.8}
#--------------------------------------------------------------------------------------------------
mega_combined_vars_df_SUBSET_added_vars %>%
  filter(country_code_ISO3 %in% c("USA", "GBR", "FRA", 'DEU')) %>%
  group_by(country_code_ISO3, year) %>%
  mutate(pwt_human_capital_index = mean(pwt_human_capital_index),
         WID_pre_tax_income_share_top_10pct = mean(WID_pre_tax_income_share_top_10pct)) %>%
  distinct(country_code_ISO3, year, .keep_all = TRUE) %>%
  ggplot(aes(x = pwt_human_capital_index,
             y = WID_pre_tax_income_share_top_10pct,
             color = country_name)) +
  geom_point() +
  labs(title = "Income Inequality vs. Human Capital Index",
       subtitle = "Country-Year Averages (1960 - 2020)",
       x = "Human Capital Index",
       y = "Income Share of Top 10%",
       caption = "
       Data source(s): Penn World Table 10.0 & World Inequality Database") +
  theme_bw() +
  theme(text = element_text(face = 'bold'),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"),
        legend.title = element_blank())
#--------------------------------------------------------------------------------------------------
```

***

```{r union_scatter1, echo=FALSE, warning=FALSE, cache=TRUE, fig.asp=0.8}
new_mega_edits_df %>%
  filter(iso3 %in% c("USA", "GBR", "FRA", 'DEU', "JPN", "CAN")) %>%
  ggplot(aes(x = oecd_union_density,
             y = pct_gdp_labor_compensation)) +
  geom_point(size = 0.75) +
  labs(title = "Union Density vs. Labor Compensation (1960-2020)",
       x = "Union Density (% Working Population)",
       y = "Labor Share of Compensation (% GDP)",
       caption = "
       Data source(s): Comparative Politics Data Set") +
  theme_bw() +
  theme(text = element_text(face = 'bold'),
        axis.title.x = element_text(vjust = -1.5),
        panel.background = element_rect(colour = "black"),
        plot.caption = element_text(hjust = 0),
        plot.caption.position = "plot",
        legend.position = "bottom",
        legend.background = element_blank(),
        legend.box.background = element_rect(colour = "black"),
        legend.title = element_blank()) +
  facet_wrap(vars(country_name))
```

***







